### PR TITLE
Sign in with Apple

### PR DESCRIPTION
**Pull request by john-royal**
This adds Sign in with Apple to the app.

Before you test:
1. Enable the "Sign in with Apple" capability for this app on the [Certificates, Identifiers, & Profiles](https://developer.apple.com/account/resources/identifiers/list) section of Apple’s developer website.
2. In the Firebase console, go to **Authentication** > **Sign-in methods** and enable Apple as a sign-in provider (already done).
3. It seems that Sign in with Apple [doesn’t work on simulators](https://developer.apple.com/forums/thread/651533), so test using a real device if at all possible.

### CODE REVIEW

**Comment by Evilsmaher** [comment]
Since it is not feasible with a simulator, may be difficult with the articles since they are simulator-based?

**Comment by john-royal** [comment]
It’s possible, but I think the pros still outweigh the cons here. More often than not, if you’re building an authentication system, you’ll want to include third-party auth.

**Comment by leftskidlow** [comment]
I think I'd come down on @Evilsmaher's side of this one, and it follows sort of the same logic. The reason I just stuck with email/password authentication when I set it up was because all the third party authentication adds no real substance to the product (it's just a click of the button on Firebase) and if you add Apple, why not add Google or Facebook, or any other number of authentication techniques. In a real app, the more functionality the better, in a teaching environment, adding things just to add them I think will turn into a bigger distractor than anything else, especially if you can't use it in the simulator.

We can, during the initial authentication article/tutorial touch on the other capabilities of Firebase of course though.

**Comment by john-royal** [comment]
Fair points. I was asked to add this because it’s on the syllabus for this skill path, so I’d want some input from @galinap684 and/or @benstone1's before I close this PR.

**Comment by benstone1** [comment]
Catching up on this now, didn't realize that the simulator didn't support it.  That's a shame, it did when I was building some of this content a couple of years ago.  The sign-in with Apple feature is a good one to know for learners because Apple requires adding it if you do want to add OAuth from another provider like Google.

Let's keep the branch around, but what we might want to do is leave it out of the final project and instead have a short article detailing other sign-in methods.  We'll see if Apple resolves this bug, but it looks like it's been over a year so I'm not holding my breath.  I'm closing this PR for now, but we can bring it back.

**Pull request closed without merging**
